name: 'Build push nodex image'
on:
  workflow_dispatch:
    inputs:
      tag:
        description: tag name
      type:
        description: 'type of image is stable or dev'
        required: true
        default: 'dev'
        type: choice
        options:
          - stable
          - dev


jobs:
  build-froint-image:
    # needs: install-back-dependencies
    runs-on: ubuntu-latest
    steps:
    - name: Use Build and Push Docker Image action
      uses: SIT-LightCode/LC-Deployment/actions/build-push-image@main
      with:
        image: "nodex"
        tags: ${{ inputs.tag }}
        type: ${{ inputs.type }}
        ghcr_pat: ${{ secrets.GHCR_PAT }}